---
abstract: 'Lexical pragma for strftime.'
author:
  - unknown
build_requires:
  Test::More: 0.96
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.56
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: lc_time
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  POSIX: 0
  parent: 0
version: 0.11
